out_folder = "outputs/"
name = "ac_cat_0.04_no_norm3"

[diffbem]
cluster_size = 128
radius_factor = 1.5
freq_bands = [1000]
n_freqs = 1
approx_ACA_tol = 1e-5
Q_ACA_tol = 1e-5
solver_tol = 1e-5
listener_ds = 5
recompute_matrices = false

[dimensions]
esize = 0.02
subdiv_top = 1
w = 0.6
b = 0.6
h = 0.15

[image]
# 0.01 ~ 128, 0.02 ~ 64
hfield_res = 128
edge_border = 2
cam_rad = 1

[optimization]
# acoustics_only | image | text | image_only | text_only
guidance_type = "image"
normalize_grads = false

# for image optim
tgt_fname = "test-data/images/cat.png"
# texture clip loss
cl_wt = 500
# renderer weights [(np.pi / 2, 0)] + [(np.pi / 4, i / 2 * np.pi) for i in range(4)]
vw_wts = [500, 200, 200, 200, 200]

# for text optim
prompt = ""
latent_iters = 10
latent_lr = 1e-1
# renderer-latent weight
rl_wt = 3

# general optim
iters = 200
save_every = 50
lr = 1e-3
init_val = 0.0
# acoustics
ac_wt = 700
# smoothness
sm_wt = 5e5
# barrier loss
vmax = 0.07
ba_wt = 3
